### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by Abd3lk4d3r** [epochtalk/epochtalk#61]
Hello I just finished Installing epochtalk and when i opened the home page : localhost:8080
it say 404 , Is this an issue or not 

Kind Of Respect .

**Comment by taesup** [comment]
Looks like you need to delete your node_modules folder and try 'npm install' again. This was a bug that we just recently fixed with node-sass and foundations. 

After you 'npm install' and if you've already run the migrate scripts, all you need to do is run 'npm run serve'

**Comment by Abd3lk4d3r** [comment]
The 404 not in the console when i run : 'sudo npm run serve' and try to host : 'localhost:8080'
all pages show 404 error , please contact administrator ,,,,,

I installed epochtalk as you describe in Readme , all went smooth . but at the end can't access any 
page when running the server . 

Thank you for your help ,
Abdelkader .

**Comment by Abd3lk4d3r** [comment]
9 days and still not getting a response , Please help me with this problem 
Kind Of Respect ,
Abdelkader .

**Comment by taesup** [comment]
It looks like a DB problem. Please make sure that it's setup correctly. Ensure that you're database.json file exists and is properly configured.

Also, please be aware that this project is not ready for public use and will change constantly. It will break often, everything from the installation process to everyday usage. The current installation process is meant for developers to understand. If you cannot install this on your own, you are free to dig into the code and try to figure out why. If you cannot do so, then please find a developer to help you. We unfortunately do not have the bandwidth to walk non-developers through the installation process especially when it is subject to change.
